<nav class="bar">
    <div class="nav-container">
    <a href="index.php">
        <img src="images/GrandTech_logo.png" title="GrandTech Logo" alt="GrandTech Logo"  height="100" class="logo">
    </a>
    <ul class="nav-menu">
        <li><a href="index.php">Home</a> </li>
        <li><a href="about.php">About</a> </li>
        <li><a href="jobs.php">Careers</a> </li>
        <li><a href="apply.php">Application</a></li>
        <li><a href="enhancements.php">Enhancements</a></li>
        <li><a href="manage.php">Admin</a></li>
        <li><a href="login.php">Login</a></li>
        <li><a href="https://github.com/106205555/project2" target="_blank">GitHub</a></li>
    </ul>
    </div>
</nav>